CREATE TABLE "user" (
                        id varchar(255) NOT NULL,
                        email varchar(255) DEFAULT NULL,
                        first_name varchar(255) DEFAULT NULL,
                        last_name varchar(255) DEFAULT NULL,
                        password varchar(255) DEFAULT NULL,
                        PRIMARY KEY (id)
);
CREATE TYPE access_type AS ENUM('private', 'public');

CREATE TABLE IF NOT EXISTS note (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(250) DEFAULT NULL,
                      contents VARCHAR(10000) DEFAULT NULL,
                      contents_short VARCHAR(100) DEFAULT NULL,
                      status access_type
);
