DELETE FROM users
WHERE email='admin@ukr.net';

ALTER TABLE users DROP CONSTRAINT users_pkey;

ALTER TABLE users DROP COLUMN id;

ALTER TABLE users
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

INSERT INTO users(email, first_name, last_name, password)
values ('admin@ukr.net',
        'admin',
        'admin',
        '{bcrypt}$2a$10$sJhCLqPnUmaGpZjLWD9scOMbIN.M1UPoK.rXZ/7n7wIyx68L56wvy');

CREATE TABLE IF NOT EXISTS user_note (
    user_id BIGINT NOT NULL,
    note_id BIGINT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(note_id) REFERENCES note(id) ON DELETE CASCADE
);